import Head from "next/head";
import {
  Contact,
  Experiences,
  Info,
  Projects,
  Skills,
  Stacks,
} from "@/components";

export default function Home() {
  return (
    <>
      <Head>
        <title>이정익 이력서</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Info />
      <Contact />
      <Stacks />
      <Projects />
      <Skills />
      <Experiences />
    </>
  );
}

export const getStaticProps = async () => {
  return {
    props: {},
  };
};
